Add basic template.
Men-Digital-Solutions/template_project_cpp pull request #1
Opened 2022-09-24 20:02 UTC by aliihsancengiz

2022-09-24 20:38 UTC, aliihsancengiz commented
Utility scripts and sanitizers will be added on different pr.

2022-09-25 14:09 UTC, hmenn commented on .github/workflows/ci.yml
> +name: Event Bus Pipeline
please change name

2022-09-25 14:12 UTC, hmenn commented on CMakeLists.txt
> +set(PROJECT_VERSION 1.0.0)
no need to define specific variable for project_version. 

project(${PROJECT_NAME}
        VERSION 1.0.0
        LANGUAGES CXX)

after this definition, you're able to access version via PROJECT_VERSION. (https://cmake.org/cmake/help/latest/variable/PROJECT_VERSION.html)

same is also applicable for PROJECT_NAME

2022-09-25 14:19 UTC, hmenn requested changes

2022-09-25 14:19 UTC, hmenn commented on CMakeLists.txt
> +	add_subdirectory(Test)
do not use tabs here. Always use spaces and for cmake it should be 4.

2022-09-25 14:19 UTC, hmenn commented on Inc/utils.hpp
> +#pragma once
please start folder names with lower cases.

Inc, Src, Test -> inc, src, test

2022-09-25 14:19 UTC, hmenn commented on Src/CMakeLists.txt
> +
follow space and tab rules

2022-09-25 14:19 UTC, hmenn commented on Src/CMakeLists.txt
> +
if it's empt, at least add ""

2022-09-25 14:19 UTC, hmenn commented on Src/main.cpp
> +	std::cout << "Hello World" << std::endl;
no tabs in code.  Generally no tab in project.

2022-09-25 14:19 UTC, hmenn commented on Src/main.cpp
> +int main()
add command line arguments as well.

2022-09-25 14:19 UTC, hmenn commented on Src/main.cpp
> +int main()
```suggestion
int main(int argc, char *argv[])
```

2022-09-25 14:19 UTC, hmenn commented on Src/utils.cpp
> +namespace common_utils {
first namespace should be project namespace.
```suggestion
namespace template_project::common_utils {
```

2022-09-25 14:19 UTC, hmenn commented on Test/CMakeLists.txt
> +	TemplateTests.cpp
filename should not start with capital case

2022-09-25 14:19 UTC, hmenn commented on Test/CMakeLists.txt
> +	PRIVATE
```suggestion
     PUBLIC
         ""
     PRIVATE
```

2022-09-27 18:52 UTC, hmenn approved these changes

2022-09-27 18:53 UTC, merged